export const languagesMap = new Map([
  ["en_US", "English (USA)"],
  ["en_UK", "English (UK)"],
  ["de", "German"],
  ["fr", "French"],
  ["ru", "Russian"],
  ["es", "Spanish"],
  ["es_LA", "Spanish (Latin-America)"],
  ["it", "Italian"],
  ["pt_BR", "Portuguese (Brazil)"],
  ["zh_CN", "Simplified Chinese (Mainland China)"],
  ["ar", "Arabic"],
  ["ja", "Japanese"],
  ["nl", "Dutch"],
  ["el", "Greek"],
  ["ro", "Romanian"],
  ["other_languages", "OTHER LANGUAGES"],
  ["af", "Afrikaans"],
  ["sq", "Albanian"],
  ["am", "Amharic"],
  ["ar_F", "Arabic (Formal)"],
  ["ar_EG", "Arabic (Egyptian)"],
  ["ar_G", "Arabic (Gulf)"],
  ["ar_L", "Arabic (Levantine)"],
  ["ar_M", "Arabic (Maghrebi)"],
  ["hy", "Armenian"],
  ["as", "Assamese"],
  ["az", "Azerbaijani"],
  ["eu", "Basque"],
  ["be", "Belarussian"],
  ["bn", "Bengali"],
  ["bs", "Bosnian"],
  ["bg", "Bulgarian"],
  ["my", "Burmese"],
  ["ca", "Catalan"],
  ["zh", "Chinese"],
  ["zh_S", "Chinese (Simplified)"],
  ["zh_TW", "Chinese (Traditional – Taiwan)"],
  ["zh_HK", "Chinese (Traditional – Hong Kong)"],
  ["zh_C", "Chinese (Traditional – Cantonese)"],
  ["zh_SH", "Chinese (Shanghainese)"],
  ["hr", "Croatian"],
  ["cs", "Czech"],
  ["da", "Danish"],
  ["fa_AF", "Dari"],
  ["et", "Estonian"],
  ["fi", "Finnish"],
  ["nl_BE", "Flemish (Belgian)"],
  ["fr_CA", "French (Canada)"],
  ["fr_CH", "French (Swiss)"],
  ["gl", "Galician"],
  ["ka", "Georgian"],
  ["de_CH", "German (Swiss)"],
  ["gu", "Gujarati"],
  ["ht", "Haitian Creole"],
  ["ha", "Hausa"],
  ["he", "Hebrew"],
  ["hi", "Hindi"],
  ["hu", "Hungarian"],
  ["is", "Icelandic"],
  ["ga", "Irish Gaelic"],
  ["id", "Indonesian"],
  ["kn", "Kannada"],
  ["kk", "Kazakh"],
  ["km", "Khmer"],
  ["ko", "Korean"],
  ["ku", "Kurdish"],
  ["lo", "Lao"],
  ["lv", "Latvian"],
  ["lt", "Lithuanian"],
  ["mk", "Macedonian"],
  ["ms", "Malay"],
  ["ml", "Malayalam"],
  ["mt", "Maltese"],
  ["mr", "Marathi"],
  ["mn", "Mongolian"],
  ["sr_ME", "Montenegrin"],
  ["ne", "Nepali"],
  ["no", "Norwegian"],
  ["ps", "Pashto"],
  ["fa", "Persian"],
  ["pl", "Polish"],
  ["pt_PT", "Portuguese (Portugal)"],
  ["pa", "Punjabi"],
  ["sr_Cyrl", "Serbian (Cyrillic)"],
  ["sr_Latn", "Serbian (Latin)"],
  ["si", "Sinhala"],
  ["sk", "Slovak"],
  ["sl", "Slovenian (Slovene)"],
  ["so", "Somali"],
  ["es_MX", "Spanish (Mexico)"],
  ["sw", "Swahili"],
  ["sv", "Swedish"],
  ["fil", "Tagalog"],
  ["tg", "Tajik"],
  ["ta", "Tamil"],
  ["te", "Telugu"],
  ["th", "Thai"],
  ["ti", "Tigrinya"],
  ["zh_TW_T", "Traditional Chinese (Taiwan)"],
  ["tr", "Turkish"],
  ["uk", "Ukrainian"],
  ["ur", "Urdu"],
  ["uz", "Uzbek"],
  ["vi", "Vietnamese"],
  ["cy", "Welsh"],
  ["xh", "Xhosa"],
  ["yi", "Yiddish"],
  ["yo", "Yoruba"],
  ["zu", "Zulu"],
]);
